services:
  #web:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: viewboth_backend
  #  volumes:
  #    - .:/backend
  #    - ./vectordb:/vectordb
  #    - ./models:/backend/models
  #    
  #  ports:
  #    - "11234:11234"
  #  env_file:
  #    - .env
  #  depends_on:
  #    - redis
  

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s