# Generated by Django 5.2.1 on 2025-06-12 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '반려동물'), ('LIFE', '생활용품'), ('ELEC', '전자기기'), ('CAR', '차량용품'), ('ETC', '기타')], max_length=100, null=True, verbose_name='카테고리')),
                ('product_name', models.CharField(max_length=200, verbose_name='제품명')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('discount_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='할인율')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('section_id', models.CharField(max_length=100, verbose_name='섹션코드')),
                ('label', models.CharField(max_length=200, verbose_name='섹션제목')),
                ('constraint', models.JSONField(blank=True, null=True, verbose_name='제약조건')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_section',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='템플릿명')),
                ('html_template', models.TextField(blank=True, null=True, verbose_name='html코드')),
                ('css_styles', models.TextField(blank=True, null=True, verbose_name='css코드')),
                ('structure_json', models.JSONField(blank=True, help_text='리포트 섹션 정의와 조건', null=True, verbose_name='템플릿구조')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_template',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='인덱스')),
                ('email', models.CharField(max_length=20, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=10, verbose_name='회원이름')),
                ('position', models.CharField(max_length=20, verbose_name='직급')),
                ('phone', models.CharField(max_length=15, verbose_name='핸드폰')),
                ('company', models.CharField(max_length=20, verbose_name='회사')),
                ('join_date', models.DateTimeField(max_length=20, verbose_name='가입일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('status', models.CharField(choices=[('created', '생성됨'), ('in_progress', '리포트 생성 중'), ('completed', '완료됨'), ('error', '에러 발생'), ('cancelled', '사용자 취소'), ('archived', '보관됨')], default='created', max_length=100)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='프로젝트아이디')),
                ('project_title', models.CharField(max_length=255, verbose_name='프로젝트명')),
                ('description', models.CharField(max_length=255, verbose_name='프로젝트설명')),
                ('created_at', models.CharField(max_length=55, verbose_name='프로젝트생성일')),
                ('updated_at', models.CharField(max_length=55, null=True, verbose_name='프로젝트수정일')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='인덱스')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', '생성 중'), ('ready', '생성 완료'), ('error', '오류 발생'), ('viewed', '사용자 확인 완료'), ('archived', '보관됨')], default='generating', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='리포트제목')),
                ('summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='리포트요약결과')),
                ('pdf_url', models.TextField(blank=True, null=True, verbose_name='pdf url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료시간')),
                ('duration', models.DurationField(verbose_name='소요시간')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.projects', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reporttemplate', verbose_name='리포트템플릿번호')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='PromptTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(verbose_name='테스트 프롬프트')),
                ('constraint_snapshot', models.JSONField(blank=True, null=True, verbose_name='테스트시점 제약조건')),
                ('question', models.TextField(max_length=500, verbose_name='생성 요청 질문')),
                ('answer', models.TextField(verbose_name='AI 응답 결과')),
                ('passed', models.BooleanField(default=False, verbose_name='응답 적합 여부')),
                ('reviewer_comment', models.TextField(blank=True, null=True, verbose_name='리뷰코멘트')),
                ('tested_at', models.DateField(auto_now_add=True, verbose_name='테스트시간')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='테스터')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='api.reportsection')),
            ],
            options={
                'db_table': 'prompt_test',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '반려동물'), ('LIFE', '생활용품'), ('ELEC', '전자기기'), ('CAR', '차량용품'), ('ETC', '기타')], max_length=100, null=True, verbose_name='카테고리')),
                ('section_code', models.CharField(max_length=100, verbose_name='섹션코드')),
                ('name', models.CharField(help_text='프롬프트 이름 (템플릿 섹션의 label)', max_length=100, verbose_name='라벨')),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='api.reportsection')),
            ],
            options={
                'db_table': 'prompt',
            },
        ),
        migrations.CreateModel(
            name='ReportSectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('generating', '생성 중'), ('ready', '생성 완료'), ('error', '오류 발생'), ('viewed', '사용자 확인 완료'), ('archived', '보관됨')], default='generating', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('section_code', models.CharField(max_length=100, verbose_name='섹션코드')),
                ('label', models.CharField(max_length=200, verbose_name='섹션제목')),
                ('content', models.TextField(verbose_name='생성된 응답')),
                ('constraint_snapshot', models.JSONField(blank=True, null=True, verbose_name='생성시점 제약조건')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.reportsection', verbose_name='참조섹션')),
            ],
            options={
                'db_table': 'report_section_result',
            },
        ),
        migrations.AddField(
            model_name='reportsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.reporttemplate', verbose_name='참조템플릿'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(verbose_name='평점')),
                ('review', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('review_date', models.CharField(max_length=100, verbose_name='작성일자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.products')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together={('template', 'section_id')},
        ),
    ]
