# Generated by Django 5.2.1 on 2025-06-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='product_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='api.products', verbose_name='자사제품'),
        ),
        migrations.AddField(
            model_name='projects',
            name='product_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='api.products', verbose_name='경쟁사제품'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='flag',
            field=models.CharField(max_length=10, null=True, verbose_name='그래프, 텍스트 여부'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='response_example',
            field=models.TextField(null=True, verbose_name='응답 예시'),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '반려동물'), ('LIFE', '생활용품'), ('ELEC', '전자기기'), ('CAR', '차량용품'), ('ETC', '기타')], max_length=100, null=True, verbose_name='상품 카테고리'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='page_chunk',
            field=models.CharField(max_length=100, null=True, verbose_name='페이지 제목'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_text',
            field=models.TextField(verbose_name='프롬프트'),
        ),
    ]
