# Generated by Django 5.2.1 on 2025-06-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects_product_1_projects_product_2_prompt_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '고양이 용품'), ('LIFE', '생활가전'), ('ELEC', '전자기기'), ('ELECACC', '헤드폰'), ('CAR', '차량용 액세서리'), ('ETC', '기타')], max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '고양이 용품'), ('LIFE', '생활가전'), ('ELEC', '전자기기'), ('ELECACC', '헤드폰'), ('CAR', '차량용 액세서리'), ('ETC', '기타')], max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '고양이 용품'), ('LIFE', '생활가전'), ('ELEC', '전자기기'), ('ELECACC', '헤드폰'), ('CAR', '차량용 액세서리'), ('ETC', '기타')], max_length=100, null=True, verbose_name='상품 카테고리'),
        ),
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.DurationField(null=True, verbose_name='소요시간'),
        ),
        migrations.AlterField(
            model_name='reportsectionresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.report'),
        ),
    ]
