# Generated by Django 5.2.1 on 2025-06-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_products_category_alter_prompt_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsectionresult',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.prompt'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.projects', verbose_name='프로젝트'),
        ),
    ]
