# Generated by Django 5.2.1 on 2025-06-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reportsectionresult_prompt_alter_report_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='section',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='section_code',
        ),
        migrations.RemoveField(
            model_name='prompttest',
            name='constraint_snapshot',
        ),
        migrations.RemoveField(
            model_name='prompttest',
            name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='prompttest',
            name='section',
        ),
        migrations.RemoveField(
            model_name='reportsectionresult',
            name='section',
        ),
        migrations.AddField(
            model_name='prompt',
            name='chunk_code',
            field=models.CharField(max_length=100, null=True, verbose_name='C코드'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='value_code',
            field=models.CharField(max_length=100, null=True, verbose_name='R코드'),
        ),
        migrations.AddField(
            model_name='prompttest',
            name='category',
            field=models.CharField(choices=[('SKIN', '스킨케어'), ('MAKE', '메이크업'), ('HAIR', '헤어케어'), ('PET', '고양이 용품'), ('LIFE', '생활가전'), ('ELEC', '전자기기'), ('ELECACC', '헤드폰'), ('CAR', '차량용 액세서리'), ('ETC', '기타')], max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='prompttest',
            name='chunk_code',
            field=models.CharField(max_length=100, null=True, verbose_name='C코드'),
        ),
        migrations.AddField(
            model_name='prompttest',
            name='value_code',
            field=models.CharField(max_length=100, null=True, verbose_name='R코드'),
        ),
        migrations.AlterField(
            model_name='prompttest',
            name='question',
            field=models.TextField(verbose_name='생성 요청 질문'),
        ),
    ]
