# Generated by Django 5.2.1 on 2025-06-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_prompt_name_remove_prompt_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='value_code',
        ),
        migrations.RemoveField(
            model_name='prompttest',
            name='value_code',
        ),
    ]
