# Generated by Django 5.2.1 on 2025-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_prompt_value_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportsectionresult",
            name="label",
        ),
        migrations.RemoveField(
            model_name="reportsectionresult",
            name="prompt",
        ),
        migrations.AddField(
            model_name="reportsectionresult",
            name="page_title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="페이지네임"
            ),
        ),
        migrations.AlterField(
            model_name="reportsectionresult",
            name="content",
            field=models.JSONField(null=True, verbose_name="생성된 응답"),
        ),
    ]
